spring:
  profiles:
    active:
    - dev
    
---

server:
  port: 7001

spring:
  profiles: dev
  application:
    name: microservicecloud-config-eureka-clinet
    
eureka:
  instance:
    hostname: eureka7001.com #eureka服务端的实例名称
  client:
    register-with-eureka: false #服务注册 false 自己不注册到服务中心
    fetchRegistry: false #服务发现  表示自己端就是注册中心 我的职责就是维护服务实例 false  自己不获取注册信息
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/  #
      
---

server:
  port: 7001
spring:
  profiles: test
  application:
    name: microservicecloud-config-eureka-clinet
    
eureka:
  instance:
    hostname: eureka7001.com #eureka服务端的实例名称
  client:
    register-with-eureka: false #服务注册 false 自己不注册到服务中心
    fetchRegistry: false #服务发现  表示自己端就是注册中心 我的职责就是维护服务实例 false  自己不获取注册信息
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/  #