spring:
  profiles:
    active:
    - dev
    
---

server:
  port: 8001

spring:
  profiles: dev
  application:
    name: microservicecloud-config-dept-clinet

mybatis:
  config-localtion: classpath:mybatis/mybatis.cfg.xml
  type-aliases-package: com.libovito.springcloud.entities
  mapper-locations: 
  - classpath:mybatis/mapper/**/*.xml

spring:
   application:
    name: microservicecloud-dept
   datasource:
     type: com.alibaba.druid.pool.DruidDataSource
     driver-class-name: org.gjt.mm.mysql.Driver
     url: jdbc:mysql://192.168.1.185:3306/cloudDB01
     username: root
     password: 123456
     dbcp2:
       min-idle: 5
       initial-size: 5
       max-total: 5
       max-wait-millis: 200

eureka:
  client:  #客户端注册进eureka服务列表内
    register-with-eureka: true #服务注册 true 注册到服务中心
    fetchRegistry: true # true 获取注册信息
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/
  instance:
    instance-id: dept-8001.com
    prefer-ip-address: true #访问路径可以显示IP地址

info:
  app.name: libovito-microservicecloud
  company.name: www.libovito.com
  build.artifactID: $project.artifactId$
  build.version: $project.version$
      
---

server:
  port: 8001

spring:
  profiles: test
  application:
    name: microservicecloud-config-clinet
    
mybatis:
  config-localtion: classpath:mybatis/mybatis.cfg.xml
  type-aliases-package: com.libovito.springcloud.entities
  mapper-locations: 
  - classpath:mybatis/mapper/**/*.xml

spring:
   application:
    name: microservicecloud-dept
   datasource:
     type: com.alibaba.druid.pool.DruidDataSource
     driver-class-name: org.gjt.mm.mysql.Driver
     url: jdbc:mysql://192.168.1.185:3306/cloudDB01
     username: root
     password: 123456
     dbcp2:
       min-idle: 5
       initial-size: 5
       max-total: 5
       max-wait-millis: 200

eureka:
  client:  #客户端注册进eureka服务列表内
    register-with-eureka: true #服务注册 true 注册到服务中心
    fetchRegistry: true # true 获取注册信息
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/
  instance:
    instance-id: dept-8001.com
    prefer-ip-address: true #访问路径可以显示IP地址

info:
  app.name: libovito-microservicecloud
  company.name: www.libovito.com
  build.artifactID: $project.artifactId$
  build.version: $project.version$